version: "3"
services:
  mysql:
    build: ./"base de datos"
    volumes:
     - ./"base de datos":/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: tecnoimport
   

