version: "3"
services:
  mysql:
    build: ./baseDatos
    volumes:
     - ./baseDatos:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: TecnoImport
   

